env:
  IMAGE_NAME: ots-image

name: Create Registry and Push image to artifact registry again
on:
  push:
    branches: [ main ]
    
  workflow_dispatch:
jobs:
  build-push-gcr:
    name: Build and Push to GCP
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Authenticate to Google
      id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.SERVICE_ACCOUNT_KEY }}' 
    
      
    - name: Build Docker Image    
      run: |-
        cd docker
        docker build -t us-central1-docker.pkg.dev/cobalt-entropy-382106/ots-project-repo-test/${{ env.IMAGE_NAME }}:latest .
    
    - name: Debug
      run: docker images
    
    - name: Configure Docker Client
      run: |-
        gcloud auth configure-docker --quiet
        gcloud auth configure-docker us-central1-docker.pkg.dev --quiet
    
    - name: Tag and Push Docker Image to Registry
      run: |-
        gcloud config get-value project
        echo "#########"
        gcloud auth configure-docker
        echo "##"
        docker push us-central1-docker.pkg.dev/cobalt-entropy-382106/ots-project-repo-test/${{ env.IMAGE_NAME }}:latest
        
        
        
