env:
  IMAGE_NAME: ots-image

name: Create Registry and Push image to artifact registry again
on:
  push:
    branches: [ main ]
    
  workflow_dispatch:
jobs:
  build-push-gcr:
    name: Build and Push to GCP
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Authenticate to Google
      id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.SERVICE_ACCOUNT_KEY }}' 
    
    - uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.1.9
        
    - name: Terraform init
      run: |- 
        cd terraform-registry
        terraform init
      
    - name: Debug
      run: echo "$GITHUB_REF"

    - name: Terraform Apply
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: |-
        cd terraform-registry 
        terraform destroy -auto-approve -input=false
        terraform apply -auto-approve -input=false
      
    - name: Build Docker Image    
      run: |-
        cd docker
        docker build -t ${{ env.IMAGE_NAME }}:latest .
    
    - name: Debug
      run: docker images
    
    - name: Configure Docker Client
      run: |-
        gcloud auth configure-docker --quiet
        gcloud auth configure-docker us-central1-docker.pkg.dev --quiet
    
    - name: Tag and Push Docker Image to Registry
      run: |-
        gcloud config get-value project
        echo "#########"
        docker image tag ${{ env.IMAGE_NAME }}:latest us-central1-docker.pkg.dev/${{ secrets.PROJECT_ID }}/ots-project-repo-test/${{ env.IMAGE_NAME }}:latest
        docker image tag ${{ env.IMAGE_NAME }}:latest us-central1-docker.pkg.dev/${{ secrets.PROJECT_ID }}/ots-project-repo-test/${{ env.IMAGE_NAME }}:${{ github.sha }}
        docker push us-central1-docker.pkg.dev/${{ secrets.PROJECT_ID }}/ots-project-repo-test/${{ env.IMAGE_NAME }}:latest
        docker push us-central1-docker.pkg.dev/${{ secrets.PROJECT_ID }}/ots-project-repo-test/${{ env.IMAGE_NAME }}:${{ github.sha }}
        
        
